modLoader="javafml"
loaderVersion="${loader_version}"
license="LGPL-3.0-or-later"
issueTrackerURL="https://github.com/TheIllusiveC4/CuriousElytra/issues"
logoFile="curiouselytra_icon.png"
logoBlur=false
[[mods]]
modId="curiouselytra"
version="${version}"
displayName="Curious Elytra"
displayURL="https://github.com/TheIllusiveC4/CuriousElytra"
authors="C4"
description='''
Adds curio support to the elytra so you can fly and wear chest armor at the same time.
'''
[[dependencies.curiouselytra]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.curiouselytra]]
    modId="minecraft"
    mandatory=true
    versionRange="${mc_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.curiouselytra]]
    modId="curios"
    mandatory=true
    versionRange="${curios_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.curiouselytra]]
    modId="caelus"
    mandatory=true
    versionRange="${caelus_version_range}"
    ordering="NONE"
    side="BOTH"
