modLoader="javafml"
loaderVersion="[27,)"
issueTrackerURL="https://github.com/TheIllusiveC4/CuriousElytra/issues"
logoFile="${mod_icon}"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_url}"
authors="${mod_author}"
description='''
${mod_description}
'''
[[dependencies.curiouselytra]]
    modId="forge"
    mandatory=true
    versionRange="[27,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.curiouselytra]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3]"
    ordering="NONE"
    side="BOTH"
[[dependencies.curiouselytra]]
    modId="caelus"
    mandatory=true
    versionRange="[FORGE-1.14.3-0.6,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.curiouselytra]]
    modId="curios"
    mandatory=true
    versionRange="[FORGE-1.14.3-0.14,)"
    ordering="NONE"
    side="BOTH"