modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/TheIllusiveC4/CuriousElytra/issues"
logoFile="${mod_icon}"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_url}"
authors="${mod_author}"
description='''
${mod_description}
'''
[[dependencies.curiouselytra]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.curiouselytra]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.curiouselytra]]
    modId="caelus"
    mandatory=true
    versionRange="[FORGE-1.16.1-2.0-beta4,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.curiouselytra]]
    modId="curios"
    mandatory=true
    versionRange="[FORGE-1.16.1-3.0-beta1,)"
    ordering="NONE"
    side="BOTH"